///住院押金
SELECT TOP 100 * from dhc_sfprintdetail WHERE prt_printdate="2019-6-25"

SELECT * FROM DHC_BillExtTradePay WHERE ETP_HisPrtStr="6542"

SELECT ETC_TradeType, * FROM DHC_BillExtTradeConSub WHERE ETC_HISPRT_DR="41689||1"

SELECT * FROM DHC_BillExtTradePay WHERE ETP_PayMode="46" AND ETP_TradeDate="2019-6-25" AND ETP_TradeType="DEP"

SELECT * FROM DHC_BillExtTradePay WHERE ETP_RowID=33188

SELECT * FROM DHC_PatientBill WHERE PB_RowId='475200'

SELECT * FROM DHC_BillConINV WHERE DHCBCI_PatBillDR='475200'

////住院发票表
SELECT PRT_ARRCP_DR, * FROM DHC_INVPRTZY WHERE PRT_Date="2019-6-25"

SELECT * FROM AR_Receipts WHERE ARRCP_Date="2019-6-25" AND ARRCP_RowId=41689

SELECT TOP 100 * FROM AR_RcptPayMode WHERE PAYM_ParRef=41689

SELECT ETC_TradeType, * FROM DHC_BillExtTradeConSub WHERE ETC_HISPRT_DR="41689||1"

SELECT * FROM DHC_BillExtTradePay WHERE ETP_RowID=33224

SELECT * FROM CT_PayMode

