

//病人基本信息表
SELECT * FROM PA_PatMas WHERE PAPMI_No='020000010083'   --11029
SELECT * FROM PA_PatMas WHERE PAPMI_RowId1="7850"

//就诊表
SELECT * FROM PA_Adm WHERE PAADM_PAPMI_DR=11029 AND PAADM_Type="I"

//住院押金表
SELECT * FROM dhc_sfprintdetail WHERE prt_paymode=4 --prt_adm_dr="17468"

SELECT * FROM CT_PayMode


//账户表
SELECT * FROM DHC_AccManager WHERE AccM_PAPMINo='020000010083'


SELECT * FROM DHC_AccPreDeposit WHERE AccPD_ParRef='44030'

//住院押金管理
SELECT * FROM PA_PatMas WHERE PAPMI_No='020000010083'   --11029
SELECT * FROM AR_Receipts WHERE ARRCP_PAPMI_DR="11029"  --13408
SELECT * FROM AR_RcptAlloc WHERE ARRAL_ARRCP_ParRef="13408"



//住院押金管理
SELECT * FROM AR_Receipts WHERE ARRCP_PAPMI_DR="6662"  --13408
SELECT * FROM AR_RcptAlloc WHERE ARRAL_ARRCP_ParRef IN (7315,7899)
//发票表的支付方式表 
SELECT * FROM Ar_rcptpaymode WHERE PAYM_ParRef=7899



//住院发票表的支付方式
SELECT c.PAYM_PayMode_DR,* FROM DHC_INVPRTZY a,AR_Receipts b,Ar_rcptpaymode c WHERE a.PRT_ARRCP_DR=b.ARRCP_RowId
AND b.ARRCP_RowId=c.PAYM_ParRef --AND c.PAYM_PayMode_DR="4"




SELECT PRT_RPFLAG,PRT_USER_DR, * from DHC_PE_INVPRT WHERE PRT_USER_DR="7579"

SELECT * FROM DHC_PE_USERREPORT WHERE RP_USER_DR="7579"


