//体检日结表
SELECT * FROM DHC_PE_USERREPORT WHERE RP_USER_DR=7579

SELECT * FROM SS_User WHERE SSUSR_RowId=7579

//体检发票表
SELECT PRT_User_DR,PRT_RPFLAG,PRT_RPUSER_DR,* FROM DHC_PE_INVPRT WHERE PRT_REPORT_DR=223

SELECT * FROM DHC_PE_INVPRT WHERE PRT_RPFLAG="Y"


SELECT * FROM DHC_PE_USERREPORT WHERE RP_ROWID=223

//体检日结支付方式表
SELECT * FROM DHC_PE_UserReportPayMode WHERE RPM_ParRef IN (198,
205,
208,
218,
223)

SELECT * FROM DHC_PE_APAmountChange

SELECT * FROM SS_User WHERE SSUSR_Name["张晓"