SELECT * FROM PA_PatMas WHERE PAPMI_No IN ('020000000094','020000017703') --PAPMI_Name IN ('范勤青')

SELECT * FROM PA_Person WHERE PAPER_Name iN ('贾诩',"徐庶")

SELECT * FROM DHC_CardRef WHERE  CF_PAPMI_DR IN (20732,20733)

SELECT * FROM PA_Adm WHERE PAADM_PAPMI_DR IN (96)

//个人基本信息表
SELECT PIBI_RowId, * FROM DHC_PE_PreIBaseInfo WHERE PIBI_PAPMINo IN ('020000015559','020000017703')
	
	//个人ADM表
SELECT  * FROM DHC_PE_PreIADM WHERE PIADM_PIBI_DR IN (17015,17657)
SELECT * FROM DHC_PE_PreIADM WHERE PIADM_RowId=22353

///体检项目表
SELECT TOP 100 IADM_CRMADM, * FROM DHC_PE_IADM WHERE IADM_CRMADM="17015"

	
	//个人项目表
SELECT PIOI_OrdEnt_DR,PIOI_ItmMast_DR, * FROM DHC_PE_PreIOrdItem WHERE PIOI_ParRef='11805'

SELECT * FROM PA_Adm WHERE PAADM_RowID IN (4048,3983)

////////////////////////////////////////////查找体检病人基本信息///////////////////
//根据登记号在个人基本信息表中找Rowid
SELECT * FROM DHC_PE_PreIBaseInfo WHERE PIBI_PAPMINo='020000000092'
	
	//根据登记号的Rowid在个人ADM表中找rowid
SELECT * FROM DHC_PE_PreIADM WHERE PIADM_PIBI_DR='10457'

	//体检人员表ADM
SELECT  * FROM DHC_PE_IADM WHERE IADM_CRMADM IN (13463)

SELECT * FROM CT_Sex


SELECT * FROM PA_Adm WHERE PAADM_RowID=4048
SELECT * FROM PA_PatMas WHERE PAPMI_RowId1=94

SELECT PA_FactAmount, * from DHC_PE_PreAudit

///体检流程管理 
SELECT * FROM DHC_PE_AdmRecordManager WHERE ARM_ADM_DR=21316