
SELECT * FROM OE_OrdItemExt WHERE OEORI_StopDripUser_DR='6878'

SELECT * FROM OE_OrdItemExt WHERE OEORI_SeeUser_DR='7490'

SELECT * FROM OE_OrdExec WHERE OEORE_OverseeUser_DR='7648'

SELECT * FROM OE_OrdExec

SELECT OEORD_Adm_DR->PAADM_PAPMI_DR->PAPMI_No, * FROM OE_Order WHERE OEORD_RowId1='55456'

SELECT PAADM_PAPMI_DR->PAPMI_No, * FROM PA_Adm WHERE PAADM_RowID=66149

SELECT * FROM PA_PatMas WHERE PAPMI_RowId1=35627

SELECT * FROM OE_OrdItem WHERE OEORI_OEORD_ParRef='55456'

SELECT OEORI_ItmMast_DR->ARCIM_Desc,OEORD_Adm_DR->PAADM_PAPMI_DR->PAPMI_No,OEORD_Adm_DR->PAADM_PAPMI_DR->PAPMI_Name,OEORE_PrintUser_DR->SSUSR_Name, c.* FROM OE_Order d, OE_OrdItem a,OE_OrdItemExt b,OE_OrdExecExt c
WHERE a.OEORI_RowId=b.OEORI_RowId
AND d.OEORD_RowId1=a.OEORI_OEORD_ParRef
AND b.OEORI_RowId=c.OEORE_OEORI_ParRef
AND c.OEORE_PrintUser_DR IN ('6878','7490','7648','7259','6865','7481','7493',"7495")
AND c.OEORE_PrintDate>'2019-10-7'

SELECT * FROM SS_User WHERE SSUSR_RowId IN ('6878','7490','7648','7259','6865','7481','7493')

SELECT TOP 100 * FROM DHC_OE_OrdExec

SELECT * FROM ARC_ItmMast WHERE ARCIM_RowId='17478||1'

SELECT * FROM OE_OrdItemExt WHERE OEORI_RowId='55456||1' 

SELECT * FROM OE_OrdExecExt WHERE OEORE_SpecCollDate="2019-9-10"


SELECT * FROM OE_OrdExecStatus WHERE STCH_User_DR='6878'