//手术表
SELECT ANAOP_Blade_DR,ANAOP_BodySite_DR, * from OR_Anaest_Operation

//手术切口
SELECT * FROM ORC_BladeType

//手术部位
SELECT * FROM OEC_BodySite WHERE BODS_RowId=71

SELECT * FROM PA_Adm WHERE PAADM_RowID=32576


SELECT * FROM DHC_AN_OPArrange WHERE OPA_Adm_Dr='32149'

SELECT * FROM DHC_AN_OPArrange WHERE OPA_RowId=349


SELECT * FROM OR_Anaesthesia WHERE ANA_PAADM_ParRef['32149'
SELECT * FROM OR_Anaesthesia WHERE ANA_RowId='32149||2'

SELECT * FROM OR_Anaest_Operation WHERE ANAOP_Par_Ref['32149'
SELECT * FROM OR_Anaest_Operation WHERE ANAOP_Par_Ref='32149||2'

///器械护士
SELECT * FROM OR_An_Oper_Scrub_Nurse WHERE OPSCN_ParRef['32149'
SELECT * FROM OR_An_Oper_Scrub_Nurse WHERE OPSCN_ParRef='32149||2||1'

SELECT * FROM CT_CareProv WHERE CTPCP_RowId1=818
