SELECT * FROM OE_Order WHERE OEORD_Adm_DR=33970

SELECT OEORI_Date, OEORI_TimeOrd,OEORI_ItmMast_DR->ARCIM_Desc,* FROM OE_OrdItem 
WHERE OEORI_OEORD_ParRef=28735  
AND OEORI_OrdDept_DR=48 
AND OEORI_ItmMast_DR->ARCIM_ItemCat_DR->ARCIC_OrdCat_DR=14


--AND OEORI_RowId IN ("28735||140","28735||149","28735||155","28735||145")

//医嘱项 
SELECT TOP 100 ARCIM_ItemCat_DR->ARCIC_OrdCat_DR, * FROM ARC_ItmMast WHERE ARCIM_ItemCat_DR=82

///医嘱子分类 
SELECT * from ARC_ItemCat WHERE ARCIC_RowId IN (57,58)
SELECT * FROM ARC_ItemCat WHERE ARCIC_OrdCat_DR=14
 
//医嘱大类 
SELECT * FROM OEC_OrderCategory WHERE ORCAT_Desc['材料'   --ORCAT_RowId=8