SELECT * FROM SS_User WHERE SSUSR_Name['冯爱'


SELECT * FROM PA_PatMas WHERE PAPMI_Name['陈圣电'

SELECT PAADM_CurrentBed_DR,* FROM PA_Adm WHERE PAADM_PAPMI_DR=32411

SELECT * FROM PAC_Bed WHERE BED_RowID IN ('11||32','4||7')

SELECT * FROM CT_Loc WHERE CTLOC_RowID IN (48,70)

SELECT * FROM OE_Order WHERE OEORD_Adm_DR=59753

SELECT * FROM OE_Order WHERE OEORD_RowId1=50224

SELECT * FROM OE_OrdItem WHERE OEORI_OEORD_ParRef=50224 AND OEORI_ItmMast_DR IN ('19796||1','19797||1')

SELECT * FROM OE_OrdItem WHERE OEORI_OEORD_ParRef=47329 AND OEORI_ItmMast_DR IN ('19796||1','19797||1')


SELECT * FROM Nur.DHCMoudData WHERE ID=11493

SELECT Item9,Item20,Item21, * FROM Nur.DHCMoudData WHERE EpisodeId=59753 AND EmrCode='DHCNURPGD_WZBRSBB'


//转移审核表
SELECT * FROM Nur.DHCNurTransAudit WHERE EpisodeId ="59753"


//转移记录表
SELECT * FROM PA_AdmTransaction WHERE TRANS_ParRef= '59753'
